services:
  grafana:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  server:
    build:
      context: ./xml-server
    ports:
      - 8001:8001
    profiles:
      - dev
      - main
      - dependency

  grafana-main:
    image: grafana/grafana:main@sha256:ea886de2567e70465bc8871307bf1a1f0ffc57c22208d0ecb60fba75e0db31e2
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:10.1.0@sha256:047c1c5aa6fef257b6c2516f95c8fcd9f28707c201c6413dd78328b6cbedff6f
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-rss-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    network_mode: host
    profiles:
      - e2e
